<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container345Zoxp\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container345Zoxp/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container345Zoxp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container345Zoxp\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container345Zoxp\srcApp_KernelProdContainer([
    'container.build_hash' => '345Zoxp',
    'container.build_id' => '766a141e',
    'container.build_time' => 1626354856,
], __DIR__.\DIRECTORY_SEPARATOR.'Container345Zoxp');
